name: Build Docker image

on:
  push:
    branches:
      - release

jobs:
  build-docker:
    runs-on: ubuntu 24
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t excalidraw .
