name: Build Docker Image on Ubuntu 22.04

on:
  push:
    branches:
      - main  # 或者你希望触发构建的分支名称

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false  # 如果你不打算推送到 Docker Hub 或其他容器注册表，则设置为 false
        tags: excalidraw:latest  # 你可以根据需要自定义镜像标签

    # 如果你打算推送到 Docker Hub 或其他容器注册表，请添加以下步骤：
    # - name: Login to Docker Hub
    #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    #   env:
    #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Push Docker image to Docker Hub
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: ${{ secrets.DOCKER_USERNAME }}/excalidraw:latest
