name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 在推送到 main 分支时触发构建
  pull_request:
    branches:
      - main  # 在针对 main 分支的 PR 时触发构建

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 登录到 Docker Hub 或其他 Docker 注册表
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # 在仓库的 Settings > Secrets 中设置
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 构建 Docker 镜像
      - name: Build Docker image
        run: |
          docker build -t b310digital/excalidraw:latest .

      # 推送 Docker 镜像到 Docker Hub
      - name: Push Docker image
        run: |
          docker push b310digital/excalidraw:latest
