name: Publish Docker Image to GitHub Packages

on:
  push:
    tags:
      - 'v*' # 当推送一个以 'v' 开头的标签时触发工作流

jobs:
  publish-docker:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t excalidraw:latest .

    - name: Save Docker image to tar file
      run: docker save -o excalidraw.tar excalidraw:latest

    - name: Log in to GitHub Packages
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image to GitHub Packages
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository }}:latest"
        docker load -i excalidraw.tar
        docker tag excalidraw:latest "$IMAGE_NAME"
        docker push "$IMAGE_NAME"
